wsi: /cluster/CBIO/data1/ablondel1/WSI_vesper_data/Embeddings/Ctranspath_m10_images/tiles
raw_path: /cluster/CBIO/data1/ablondel1/WSI_vesper_data/
table_data: /cluster/CBIO/data1/ablondel1/WSI_vesper_data/split_test_3.csv
batch_size: 16
dropout: 0.4
feature_depth: 768 
lr: 0.003
num_workers: 1
model_name: mhmc_layers
nb_tiles: 200
epochs: 1000
target_name: target
ref_metric: loss

