wsi: /Users/aliceblondel/Desktop/WSI_vesper/data/Embeddings_complete/ctranspath/level_2/
raw_path: /Users/aliceblondel/Desktop/WSI_vesper/data/
table_data: /Users/aliceblondel/Desktop/WSI_vesper/data/split_test_4.csv
batch_size: 16
dropout: 0.4
feature_depth: 256 
lr: 0.003
num_workers: 1
model_name: mhmc_layers
nb_tiles: 200
epochs: 200
target_name: output_variable
ref_metric: loss

